# Generated by Django 5.2.17 on 2026-10-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop_name', models.CharField(default='My Shop', max_length=160)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gstin', models.CharField(blank=True, max_length=20, verbose_name='GSTIN')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business/')),
            ],
            options={
                'db_table': 'business_settings',
            },
        ),
        migrations.CreateModel(
            name='HardwareSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barcode_scanner_enabled', models.BooleanField(default=True)),
                ('scanner_autofocus', models.BooleanField(default=True, help_text='Keep the POS barcode box focused for the scanner')),
                ('thermal_printer_enabled', models.BooleanField(default=False)),
                ('thermal_paper_width', models.PositiveSmallIntegerField(choices=[(58, '58 mm'), (80, '80 mm')], default=80)),
                ('auto_print_receipt', models.BooleanField(default=False)),
                ('label_printer_enabled', models.BooleanField(default=False)),
                ('label_width_mm', models.PositiveSmallIntegerField(default=50)),
                ('label_height_mm', models.PositiveSmallIntegerField(default=25)),
                ('cash_drawer_enabled', models.BooleanField(default=False, help_text='Drawer wired to the receipt printer (opens on print)')),
                ('customer_display_enabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'hardware_settings',
            },
        ),
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_prefix', models.CharField(default='INV-', max_length=10)),
                ('receipt_title', models.CharField(default='TAX INVOICE', max_length=80)),
                ('footer', models.CharField(blank=True, default='Thank you! Visit again.', max_length=255)),
                ('paper_format', models.CharField(choices=[('THERMAL_80', 'Thermal 80 mm'), ('THERMAL_58', 'Thermal 58 mm'), ('A4', 'A4')], default='THERMAL_80', max_length=12)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, help_text='GST % added on top of item prices', max_digits=5)),
            ],
            options={
                'db_table': 'invoice_settings',
            },
        ),
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash_enabled', models.BooleanField(default=True)),
                ('upi_enabled', models.BooleanField(default=True)),
                ('upi_id', models.CharField(blank=True, max_length=80)),
                ('card_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'payment_settings',
            },
        ),
    ]
